addons:
  firefox: 54.0

services:
  - xvfb

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.5.6
      script:
        - bundle exec danger
    - rvm: 2.5.6
      env:
        - GRAPE_SWAGGER_VERSION=0.8.0
    - rvm: 2.5.6
      env:
        - GRAPE_SWAGGER_VERSION=0.9.0
    - rvm: 2.5.6
      env:
        - GRAPE_SWAGGER_VERSION=0.11.0
    - rvm: 2.5.6
      env:
        - GRAPE_SWAGGER_VERSION=0.20.2
    - rvm: 2.5.6
      env:
        - GRAPE_SWAGGER_VERSION=0.33.0
    - rvm: 2.5.6
      env:
        - GRAPE_SWAGGER_VERSION=HEAD
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - env: GRAPE_SWAGGER_VERSION=HEAD
    - rvm: ruby-head
    - rvm: jruby-head
